// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpViUMU754DCZ74rG1A7mrQK0bSiQf22E',
    appId: '1:493956810676:web:d800bb49ae729d51d8d4e1',
    messagingSenderId: '493956810676',
    projectId: 'musicx-e8250',
    authDomain: 'musicx-e8250.firebaseapp.com',
    storageBucket: 'musicx-e8250.appspot.com',
    measurementId: 'G-RS6994DSNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7xXb4rBi9KZqjuacotBmSEzdC4GQIHNg',
    appId: '1:493956810676:android:cf8c32c81abc3fdcd8d4e1',
    messagingSenderId: '493956810676',
    projectId: 'musicx-e8250',
    storageBucket: 'musicx-e8250.appspot.com',
  );

}